name = "AoC-2021"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021, Jacob Williams"
license = "BSD-3"
description = "Advent of Code 2021 with Fortran"
homepage = "https://github.com/jacobwilliams/AoC-2021"
keywords = ["AOC"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = false
